apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-drone-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-drone-test
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: <YOUR-SECRET-NAME>
      containers:
        - name: hello-drone-test
          image: DOCKER-REPO:testing-hello-drone
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /ssh
          env:
            - name: SPRING_DATASOURCE_DB2_USERNAME
              valueFrom:
                secretKeyRef:
                  name: SECRET-NAME
                  key: username
            - name: SPRING_DATASOURCE_DB2_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: SECRET-NAME
key: password
