apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-drone-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-drone-test
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: <YOUR-SECRET-NAME>
      containers:
        - name: cloud-drone-test
          image: DOCKER-REPO:testing-hello-drone
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /ssh
